export const deckCostBands = {
	allPricesNote: 'All guide prices below are including GST.',
	minimumJob: {
		label: 'Very small deck',
		price: 'from around $4,000',
		size: 'approximately 6m²',
	},
	basicGroundLevelPerM2: '$495-$770+/m²',
	typicalSmallDeckTotal: '$6,000-$8,000',
	hardwoodSweetSpotTotal: '$12,000-$15,000+',
	exampleTotals: [
		{
			size: '10m²+',
			total: 'around $6,000-$7,700+',
			note: 'includes small-job setup/loading and aligns with typical small-deck budgeting',
		},
		{
			size: '20m²+',
			total: 'around $10,000-$15,500+',
			note: 'often where framing, access, and detailing become clearer cost drivers',
		},
		{
			size: '30m²+',
			total: 'around $15,000-$23,000+',
			note: 'layout, access, and structure can move this significantly',
		},
	],
	timberSpeciesPerM2: {
		merbau: 'around $560/m²',
		spottedGum: 'around $675/m²',
		blackbutt: 'around $690/m²',
	},
	reboardingPerM2: '$300-$600/m²',
	demolition: {
		minimum: 'minimum around $1,000',
		upper: '$10,000-$12,000+',
	},
	subframeUpgradePerM2: '$150-$200/m²',
	stairsPerGoing: '$200-$300 per standard going/riser',
	balustradesPerLm: {
		timber: '$300-$600/lm',
		glass: '$400-$550/lm',
		wire: '$350-$500/lm',
	},
	poolDeckingPerM2: '$600-$1,000/m²',
	poolDeckingPremium: 'usually at least 15% more than a simple alfresco deck',
	maintenance: {
		initialOrMaintenanceOil: '$40/m² plus $150 callout fee',
		annualMaintenance: '$60/m² plus $150 callout fee',
		heavyRestorationPerDay: '$1,500-$2,000 per day',
		frequencyExposed: 'every 6-12 months',
		frequencyProtected: 'every 12-24 months',
	},
	exclusions: [
		'design',
		'engineering',
		'permits',
		'demolition',
		'rubbish removal',
		'excavation',
		'drainage',
		'concrete footings',
		'balustrades',
		'stairs',
		'lighting',
		'seating',
		'screens',
		'planter boxes',
		'pool coping',
		'difficult access',
		'structural remediation',
	],
} as const;
